# -*- coding: utf-8 -*-
from selenium.webdriver.firefox.webdriver import WebDriver
from selenium.webdriver.common.action_chains import ActionChains
import time, unittest

def is_alert_present(wd):
    try:
        wd.switch_to_alert().text
        return True
    except:
        return False

class login2(unittest.TestCase):
    def setUp(self):
        self.wd = WebDriver()
        self.wd.implicitly_wait(60)
    
    def test_login2(self):
        success = True
        wd = self.wd
        wd.get("http://localhost:8080/php4dvd/?go=movie&id=4&name=test2")
        ActionChains(wd).move_to_element(wd.find_element_by_css_selector("div.content-wrapper")).perform()
        ActionChains(wd).move_to_element(wd.find_element_by_css_selector("div.content-wrapper")).perform()
        ActionChains(wd).move_to_element(wd.find_element_by_css_selector("div.login-box-body")).perform()
        ActionChains(wd).move_to_element(wd.find_element_by_css_selector("p.login-box-msg")).perform()
        ActionChains(wd).move_to_element(wd.find_element_by_id("username")).perform()
        wd.find_element_by_id("username").click()
        ActionChains(wd).move_to_element(wd.find_element_by_id("loginform")).perform()
        ActionChains(wd).move_to_element(wd.find_element_by_id("password")).perform()
        wd.find_element_by_id("username").click()
        wd.find_element_by_id("username").send_keys("\\undefined")
        wd.find_element_by_id("password").click()
        ActionChains(wd).move_to_element(wd.find_element_by_id("loginform")).perform()
        ActionChains(wd).move_to_element(wd.find_element_by_id("username")).perform()
        wd.find_element_by_id("password").click()
        wd.find_element_by_id("password").clear()
        wd.find_element_by_id("password").send_keys("admin")
        ActionChains(wd).move_to_element(wd.find_element_by_id("loginform")).perform()
        ActionChains(wd).move_to_element(wd.find_element_by_id("password")).perform()
        ActionChains(wd).move_to_element(wd.find_element_by_id("loginform")).perform()
        ActionChains(wd).move_to_element(wd.find_element_by_xpath("//div[@class='col-xs-4']//button[.='Log in']")).perform()
        wd.find_element_by_id("password").click()
        wd.find_element_by_id("password").send_keys("\\undefined")
        wd.find_element_by_xpath("//div[@class='col-xs-4']//button[.='Log in']").click()
        ActionChains(wd).move_to_element(wd.find_element_by_css_selector("footer.main-footer")).perform()
        ActionChains(wd).move_to_element(wd.find_element_by_css_selector("div.content-wrapper")).perform()
        ActionChains(wd).move_to_element(wd.find_element_by_xpath("//div[@id='movie_2']//div[.='test1']")).perform()
        ActionChains(wd).move_to_element(wd.find_element_by_css_selector("div.movies")).perform()
        ActionChains(wd).move_to_element(wd.find_element_by_css_selector("div.movie-nocover")).perform()
        ActionChains(wd).move_to_element(wd.find_element_by_id("movie_1")).perform()
        ActionChains(wd).move_to_element(wd.find_element_by_xpath("//div[@id='movie_2']/div[1]/div")).perform()
        ActionChains(wd).move_to_element(wd.find_element_by_id("movie_2")).perform()
        ActionChains(wd).move_to_element(wd.find_element_by_css_selector("div.movie-nocover")).perform()
        ActionChains(wd).move_to_element(wd.find_element_by_css_selector("div.movies")).perform()
        ActionChains(wd).move_to_element(wd.find_element_by_css_selector("section.content")).perform()
        ActionChains(wd).move_to_element(wd.find_element_by_link_text("Add movie")).perform()
        ActionChains(wd).move_to_element(wd.find_element_by_link_text("Add movie")).perform()
        ActionChains(wd).move_to_element(wd.find_element_by_link_text("Add movie")).perform()
        ActionChains(wd).move_to_element(wd.find_element_by_link_text("Add movie")).perform()
        wd.find_element_by_link_text("Add movie").click()
        ActionChains(wd).move_to_element(wd.find_element_by_link_text("Save")).perform()
        ActionChains(wd).move_to_element(wd.find_element_by_css_selector("div.content-wrapper")).perform()
        ActionChains(wd).move_to_element(wd.find_element_by_css_selector("div.col-md-6")).perform()
        ActionChains(wd).move_to_element(wd.find_element_by_xpath("//div[@class='col-md-12']/div[2]/div/div")).perform()
        ActionChains(wd).move_to_element(wd.find_element_by_xpath("//form[@id='updateform']/div[1]/div[3]/div")).perform()
        ActionChains(wd).move_to_element(wd.find_element_by_id("aka")).perform()
        ActionChains(wd).move_to_element(wd.find_element_by_id("name")).perform()
        wd.find_element_by_id("name").click()
        wd.find_element_by_id("name").clear()
        wd.find_element_by_id("name").send_keys("test3")
        ActionChains(wd).move_to_element(wd.find_element_by_xpath("//form[@id='updateform']/div[1]/div[2]/div")).perform()
        ActionChains(wd).move_to_element(wd.find_element_by_id("name")).perform()
        ActionChains(wd).move_to_element(wd.find_element_by_id("aka")).perform()
        ActionChains(wd).move_to_element(wd.find_element_by_xpath("//form[@id='updateform']/div[1]")).perform()
        ActionChains(wd).move_to_element(wd.find_element_by_css_selector("div.col-sm-9")).perform()
        ActionChains(wd).move_to_element(wd.find_element_by_id("year")).perform()
        wd.find_element_by_id("name").click()
        wd.find_element_by_id("name").send_keys("\\undefined")
        wd.find_element_by_id("year").click()
        ActionChains(wd).move_to_element(wd.find_element_by_id("year-error")).perform()
        ActionChains(wd).move_to_element(wd.find_element_by_id("aka")).perform()
        wd.find_element_by_id("year").click()
        wd.find_element_by_id("year").clear()
        wd.find_element_by_id("year").send_keys("2003")
        ActionChains(wd).move_to_element(wd.find_element_by_xpath("//form[@id='updateform']/div[1]")).perform()
        ActionChains(wd).move_to_element(wd.find_element_by_xpath("//form[@id='updateform']/div[1]/div[5]")).perform()
        ActionChains(wd).move_to_element(wd.find_element_by_xpath("//form[@id='updateform']/div[1]")).perform()
        ActionChains(wd).move_to_element(wd.find_element_by_xpath("//label[@for='rating']")).perform()
        wd.find_element_by_id("year").click()
        wd.find_element_by_id("year").send_keys("\\undefined")
        wd.find_element_by_xpath("//label[@for='rating']").click()
        wd.find_element_by_id("rating").click()
        ActionChains(wd).move_to_element(wd.find_element_by_xpath("//label[@for='cover']")).perform()
        ActionChains(wd).move_to_element(wd.find_element_by_xpath("//label[@for='trailer']")).perform()
        ActionChains(wd).move_to_element(wd.find_element_by_xpath("//label[@for='notes']")).perform()
        ActionChains(wd).move_to_element(wd.find_element_by_xpath("//form[@id='updateform']/div[1]/div[16]")).perform()
        ActionChains(wd).move_to_element(wd.find_element_by_id("notes")).perform()
        ActionChains(wd).move_to_element(wd.find_element_by_id("subtitles")).perform()
        ActionChains(wd).move_to_element(wd.find_element_by_id("writer")).perform()
        ActionChains(wd).move_to_element(wd.find_element_by_id("music")).perform()
        ActionChains(wd).move_to_element(wd.find_element_by_xpath("//form[@id='updateform']/div[1]")).perform()
        ActionChains(wd).move_to_element(wd.find_element_by_css_selector("div.content-wrapper")).perform()
        ActionChains(wd).move_to_element(wd.find_element_by_css_selector("div.col-md-12")).perform()
        ActionChains(wd).move_to_element(wd.find_element_by_id("submit")).perform()
        wd.find_element_by_id("submit").click()
        ActionChains(wd).move_to_element(wd.find_element_by_id("producer")).perform()
        ActionChains(wd).move_to_element(wd.find_element_by_xpath("//form[@id='updateform']/div[1]")).perform()
        ActionChains(wd).move_to_element(wd.find_element_by_css_selector("div.content-wrapper")).perform()
        ActionChains(wd).move_to_element(wd.find_element_by_css_selector("html")).perform()
        ActionChains(wd).move_to_element(wd.find_element_by_css_selector("a.dropdown-toggle")).perform()
        ActionChains(wd).move_to_element(wd.find_element_by_xpath("//header[@class='main-header']/nav/div[3]/ul/li[1]/a")).perform()
        ActionChains(wd).move_to_element(wd.find_element_by_css_selector("i.fa.fa-wrench")).perform()
        ActionChains(wd).move_to_element(wd.find_element_by_css_selector("i.fa.fa-wrench")).perform()
        ActionChains(wd).move_to_element(wd.find_element_by_css_selector("a.dropdown-toggle")).perform()
        wd.find_element_by_css_selector("a.dropdown-toggle").click()
        ActionChains(wd).move_to_element(wd.find_element_by_css_selector("i.fa.fa-wrench")).perform()
        ActionChains(wd).move_to_element(wd.find_element_by_css_selector("ul.dropdown-menu")).perform()
        ActionChains(wd).move_to_element(wd.find_element_by_link_text("User management")).perform()
        ActionChains(wd).move_to_element(wd.find_element_by_link_text("My profile")).perform()
        ActionChains(wd).move_to_element(wd.find_element_by_link_text("Log out")).perform()
        wd.find_element_by_link_text("Log out").click()
        ActionChains(wd).move_to_element(wd.find_element_by_css_selector("div.content-wrapper")).perform()
        ActionChains(wd).move_to_element(wd.find_element_by_css_selector("html")).perform()
        ActionChains(wd).move_to_element(wd.find_element_by_css_selector("footer.main-footer")).perform()
        ActionChains(wd).move_to_element(wd.find_element_by_css_selector("div.content-wrapper")).perform()
        self.assertTrue(success)
    
    def tearDown(self):
        self.wd.quit()

if __name__ == '__main__':
    unittest.main()
